import { createThemeStyles } from "./createThemeStyles";

export const callTicketStyles = createThemeStyles({
  container: { flex: 1, backgroundColor: "#f9fafb" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 14,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  title: { fontSize: 22, fontWeight: "700", color: "#111827", marginBottom: 4 },
  subtitle: { fontSize: 13, color: "#6b7280" },
  backButton: { paddingBottom: 10 },
  backButtonText: { color: "#6b7280", fontSize: 15 },
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  tabActive: { borderBottomWidth: 2, borderBottomColor: "#2563eb" },
  tabText: { fontSize: 14, color: "#9ca3af" },
  tabTextActive: { color: "#2563eb", fontWeight: "700" },
  // Ticket card
  ticketCard: {
    marginHorizontal: 12,
    marginVertical: 6,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  ticketTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  ticketDuration: { fontSize: 18, fontWeight: "700", color: "#1e40af" },
  ticketPrice: { fontSize: 16, fontWeight: "700", color: "#059669" },
  sellerName: { fontSize: 13, color: "#6b7280", marginBottom: 10 },
  purchaseButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
  purchaseButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "700" },
  // Create ticket form
  createSection: {
    margin: 12,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  lockedMeta: {
    fontSize: 13,
    color: "#374151",
    fontWeight: "700",
    marginBottom: 8,
  },
  lockedItem: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 4,
  },
  rankGuideButton: {
    marginTop: 10,
    alignSelf: "flex-start",
    borderRadius: 8,
    backgroundColor: "#374151",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  rankGuideButtonText: {
    fontSize: 12,
    color: "#f9fafb",
    fontWeight: "700",
  },
  createTitle: { fontSize: 15, fontWeight: "700", color: "#111827", marginBottom: 12 },
  label: { fontSize: 13, color: "#374151", marginBottom: 4, marginTop: 10 },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 15,
    color: "#111827",
  },
  createButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 16,
  },
  createButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "700" },
  // Purchase history
  purchasedCard: {
    marginHorizontal: 12,
    marginVertical: 6,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  purchasedTitle: { fontSize: 14, fontWeight: "600", color: "#111827", marginBottom: 4 },
  purchasedMeta: { fontSize: 12, color: "#6b7280", marginBottom: 6 },
  usedBadge: {
    backgroundColor: "#f3f4f6",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: "flex-start",
  },
  usedBadgeText: { fontSize: 11, color: "#9ca3af" },
  useButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    marginTop: 6,
  },
  useButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "600" },
  emptyText: { textAlign: "center", color: "#9ca3af", paddingTop: 40, fontSize: 14 },
});
