import { createThemeStyles } from "./createThemeStyles";

export const chatStyles = createThemeStyles({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 8,
  },
  backButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 24,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  snackbarContainer: {
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 4,
    backgroundColor: "#c3edc8",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  snackbarText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  quotaInfoBox: {
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 4,
    borderRadius: 8,
    backgroundColor: "#eef2ff",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  quotaInfoText: {
    color: "#1f2937",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  actionRow: {
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  meetButton: {
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  meetButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  meetDecisionRow: {
    flexDirection: "row",
    gap: 8,
  },
  meetDecisionButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  acceptButton: {
    backgroundColor: "#16a34a",
  },
  rejectButton: {
    backgroundColor: "#dc2626",
  },
  meetDecisionButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  inactiveQrButton: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: "#d1d5db",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  inactiveQrButtonText: {
    color: "#374151",
    fontWeight: "600",
  },
  activeQrButton: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  activeQrButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  reviewButton: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: "#7c3aed",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  reviewButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  messageContainer: {
    margin: 10,
    maxWidth: "80%",
  },
  senderMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#e74c3c",
    borderRadius: 15,
  },
  receiverMessage: {
    alignSelf: "flex-start",
    backgroundColor: "#f0f0f0",
    borderRadius: 15,
  },
  messageText: {
    padding: 10,
    color: "#000",
  },
  senderMessageText: {
    color: "white",
  },
  messageStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  readIndicator: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: "600",
  },
  inputContainer: {
    flexDirection: "row",
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    borderRadius: 20,
    marginRight: 10,
  },
  button: {
    backgroundColor: "#e74c3c",
    paddingHorizontal: 20,
    justifyContent: "center",
    borderRadius: 20,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
  },
  emptyText: {
    textAlign: "center",
    color: "#999",
    marginTop: 20,
  },
  statusInfoBox: {
    marginHorizontal: 12,
    marginBottom: 8,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    padding: 10,
  },
  statusInfoText: {
    color: "#374151",
    fontSize: 13,
    textAlign: "center",
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 12,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
  },
  pickerTrigger: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: "#ffffff",
  },
  pickerTriggerLabel: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 2,
  },
  pickerTriggerValue: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
  meetSpotLabel: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  meetSpotGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  meetSpotButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#f9fafb",
  },
  meetSpotButtonSelected: {
    borderColor: "#2563eb",
    backgroundColor: "#dbeafe",
  },
  meetSpotButtonText: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "600",
  },
  meetSpotButtonTextSelected: {
    color: "#1d4ed8",
  },
  mapApplyButton: {
    backgroundColor: "#1d4ed8",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    marginBottom: 8,
  },
  mapApplyButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  customMeetMetaText: {
    color: "#374151",
    fontSize: 12,
    marginBottom: 8,
  },
  placePickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  placePickerCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: "80%" as any,
  },
  placeSearchRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  placeSearchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
  },
  placeSearchButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  placeSearchButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  placeResultList: {
    maxHeight: 320,
  },
  placeResultItem: {
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  placeResultName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  placeResultAddress: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 2,
  },
  placePickerCancelButton: {
    backgroundColor: "#9ca3af",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    marginTop: 12,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 4,
  },
  modalButton: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  modalCancelButton: {
    backgroundColor: "#9ca3af",
  },
  modalSubmitButton: {
    backgroundColor: "#2563eb",
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    padding: 20,
  },
  pickerCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    maxHeight: "85%" as any,
  },
  calendarHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarNavButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarNavButtonText: {
    color: "#374151",
    fontWeight: "700",
  },
  calendarTitleText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  calendarWeekRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  calendarWeekText: {
    width: "14.2857%" as any,
    textAlign: "center",
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  calendarCellBlank: {
    width: "14.2857%" as any,
    height: 36,
  },
  calendarCell: {
    width: "14.2857%" as any,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarCellSelected: {
    backgroundColor: "#2563eb",
  },
  calendarCellText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  calendarCellTextSelected: {
    color: "#ffffff",
  },
  timeList: {
    maxHeight: 260,
    marginBottom: 12,
  },
  timeOptionButton: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: "#f9fafb",
  },
  timeOptionButtonSelected: {
    backgroundColor: "#dbeafe",
    borderColor: "#2563eb",
  },
  timeOptionText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "600",
  },
  timeOptionTextSelected: {
    color: "#1d4ed8",
  },
  pickerCancelButton: {
    backgroundColor: "#9ca3af",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
});
