import { createThemeStyles } from "./createThemeStyles";

export const fanclubStyles = createThemeStyles({
  container: { flex: 1, backgroundColor: "#fafafa" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 14,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  title: { fontSize: 22, fontWeight: "700", color: "#111827", marginBottom: 4 },
  subtitle: { fontSize: 13, color: "#6b7280" },
  backButton: { paddingBottom: 10 },
  backButtonText: { color: "#6b7280", fontSize: 15 },
  // Creator info card
  creatorCard: {
    margin: 12,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  creatorName: { fontSize: 18, fontWeight: "700", color: "#111827", marginBottom: 8 },
  memberCountText: { fontSize: 14, color: "#6b7280", marginBottom: 4 },
  priceText: { fontSize: 14, color: "#374151", marginBottom: 14 },
  subscribeButton: {
    backgroundColor: "#7c3aed",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  subscribeButtonText: { color: "#ffffff", fontSize: 15, fontWeight: "700" },
  subscribedBadge: {
    backgroundColor: "#ede9fe",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
  subscribedBadgeText: { color: "#7c3aed", fontSize: 14, fontWeight: "700" },
  cancelButton: {
    marginTop: 8,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  cancelButtonText: { color: "#6b7280", fontSize: 13 },
  // Subscription list
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#374151",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  itemCard: {
    marginHorizontal: 12,
    marginVertical: 5,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  itemName: { fontSize: 15, fontWeight: "600", color: "#111827", marginBottom: 4 },
  itemMeta: { fontSize: 12, color: "#6b7280", marginBottom: 2 },
  statusActive: { color: "#059669", fontWeight: "600" },
  statusInactive: { color: "#9ca3af" },
  lockGuideCard: {
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#ddd6fe",
    borderRadius: 10,
    backgroundColor: "#f5f3ff",
    padding: 12,
  },
  lockGuideTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#6d28d9",
    marginBottom: 4,
  },
  lockGuideText: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 4,
  },
  lockGuideProgressText: {
    fontSize: 12,
    color: "#6d28d9",
    fontWeight: "600",
    marginBottom: 8,
  },
  lockGuideButton: {
    alignSelf: "flex-start",
    backgroundColor: "#7c3aed",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  lockGuideButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyText: { textAlign: "center", color: "#9ca3af", paddingTop: 40, fontSize: 14 },
});
