import { createThemeStyles } from "./createThemeStyles";

export const giftStyles = createThemeStyles({
  container: { flex: 1, backgroundColor: "#fff0f6" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 14,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#fce7f3",
  },
  title: { fontSize: 22, fontWeight: "700", color: "#be185d", marginBottom: 4 },
  subtitle: { fontSize: 13, color: "#9ca3af" },
  backButton: { paddingBottom: 10 },
  backButtonText: { color: "#9ca3af", fontSize: 15 },
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#fce7f3",
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: "center" },
  tabActive: { borderBottomWidth: 2, borderBottomColor: "#ec4899" },
  tabText: { fontSize: 14, color: "#9ca3af" },
  tabTextActive: { color: "#ec4899", fontWeight: "700" },
  // Send tab
  sendContainer: { padding: 12 },
  recipientLabel: { fontSize: 13, color: "#374151", marginBottom: 6, fontWeight: "600" },
  recipientInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#fbcfe8",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 15,
    color: "#111827",
    marginBottom: 14,
  },
  itemsTitle: { fontSize: 13, color: "#374151", fontWeight: "600", marginBottom: 8 },
  itemsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  giftItemButton: {
    width: "46%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fbcfe8",
  },
  giftItemButtonSelected: {
    borderColor: "#ec4899",
    backgroundColor: "#fdf2f8",
  },
  giftItemEmoji: { fontSize: 28, marginBottom: 4 },
  giftItemName: { fontSize: 12, color: "#374151", textAlign: "center", marginBottom: 2 },
  giftItemPrice: { fontSize: 12, color: "#9ca3af" },
  giftItemPriceSelected: { color: "#ec4899", fontWeight: "700" },
  sendButton: {
    backgroundColor: "#ec4899",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 16,
  },
  sendButtonText: { color: "#ffffff", fontSize: 15, fontWeight: "700" },
  sendButtonDisabled: { backgroundColor: "#f9a8d4" },
  lockGuideCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#fbcfe8",
    borderRadius: 10,
    backgroundColor: "#fff1f2",
    padding: 12,
  },
  lockGuideTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#be123c",
    marginBottom: 4,
  },
  lockGuideText: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 4,
  },
  lockGuideProgressText: {
    fontSize: 12,
    color: "#be123c",
    fontWeight: "600",
    marginBottom: 8,
  },
  lockGuideButton: {
    alignSelf: "flex-start",
    backgroundColor: "#ec4899",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  lockGuideButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  // Received list
  giftCard: {
    marginHorizontal: 12,
    marginVertical: 5,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#fce7f3",
    flexDirection: "row",
    alignItems: "center",
  },
  giftCardTouchable: {
    flexDirection: "row",
    alignItems: "center",
  },
  giftEmoji: { fontSize: 32, marginRight: 12 },
  giftInfo: { flex: 1 },
  giftName: { fontSize: 15, fontWeight: "600", color: "#111827", marginBottom: 2 },
  giftFrom: { fontSize: 12, color: "#6b7280", marginBottom: 2 },
  giftPrice: { fontSize: 12, color: "#ec4899", fontWeight: "600" },
  giftDate: { fontSize: 11, color: "#9ca3af" },
  unopenedBadge: {
    backgroundColor: "#fce7f3",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  unopenedBadgeText: { fontSize: 11, color: "#ec4899", fontWeight: "600" },
  emptyText: { textAlign: "center", color: "#9ca3af", paddingTop: 40, fontSize: 14 },
});
