import { createThemeStyles } from "./createThemeStyles";

export const liveStyles = createThemeStyles({
  container: { flex: 1, backgroundColor: "#0f0f0f" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0f0f0f",
  },
  header: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 12, backgroundColor: "#1a1a1a" },
  title: { fontSize: 22, fontWeight: "700", color: "#ffffff", marginBottom: 4 },
  subtitle: { fontSize: 13, color: "#9ca3af" },
  tabRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#2d2d2d",
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
  },
  tabItemActive: {
    borderBottomWidth: 2,
    borderBottomColor: "#ef4444",
  },
  tabText: {
    color: "#6b7280",
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#ef4444",
  },
  liveCard: {
    marginHorizontal: 12,
    marginVertical: 6,
    backgroundColor: "#1e1e1e",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#2d2d2d",
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#ef4444", marginRight: 6 },
  liveText: { fontSize: 11, fontWeight: "700", color: "#ef4444", letterSpacing: 1 },
  streamTitle: { fontSize: 16, fontWeight: "700", color: "#ffffff", marginBottom: 4 },
  broadcasterName: { fontSize: 13, color: "#9ca3af", marginBottom: 10 },
  statsRow: { flexDirection: "row", gap: 16 },
  statItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  statText: { fontSize: 12, color: "#6b7280" },
  enterButton: {
    backgroundColor: "#ef4444",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    marginTop: 10,
  },
  enterButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "700" },
  emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center", paddingTop: 80 },
  emptyText: { fontSize: 14, color: "#6b7280", textAlign: "center" },
  // Stream detail
  detailContainer: { flex: 1, backgroundColor: "#0f0f0f" },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: "#1a1a1a",
  },
  backButton: { paddingRight: 12 },
  backButtonText: { color: "#9ca3af", fontSize: 16 },
  detailTitle: { flex: 1, fontSize: 16, fontWeight: "700", color: "#ffffff" },
  detailBroadcaster: { fontSize: 13, color: "#9ca3af", paddingHorizontal: 16, marginTop: 8 },
  tipSection: { paddingHorizontal: 16, paddingTop: 20 },
  sectionLabel: { fontSize: 14, fontWeight: "700", color: "#d1d5db", marginBottom: 12 },
  tipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tipButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#2d2d2d",
    borderRadius: 20,
  },
  tipButtonText: { color: "#fbbf24", fontSize: 13, fontWeight: "600" },
  tipProcessing: { backgroundColor: "#374151" },
  totalTipping: { fontSize: 14, color: "#fbbf24", paddingHorizontal: 16, marginTop: 16 },
  endButton: {
    marginHorizontal: 16,
    marginTop: 24,
    backgroundColor: "#374151",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  endButtonText: { color: "#f87171", fontSize: 14, fontWeight: "600" },
  myStreamButton: {
    margin: 12,
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  myStreamButtonText: { color: "#ef4444", fontSize: 15, fontWeight: "700" },
  rankLockCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#374151",
  },
  rankLockTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#f3f4f6",
    marginBottom: 6,
  },
  rankLockMeta: {
    fontSize: 12,
    color: "#9ca3af",
    marginBottom: 4,
    fontWeight: "600",
  },
  rankLockItem: {
    fontSize: 12,
    color: "#d1d5db",
    marginBottom: 4,
  },
  rankLockButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderRadius: 8,
    backgroundColor: "#374151",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  rankLockButtonText: {
    fontSize: 12,
    color: "#e5e7eb",
    fontWeight: "700",
  },
  startStreamSection: { paddingHorizontal: 16, paddingTop: 20 },
  titleInput: {
    backgroundColor: "#1e1e1e",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#ffffff",
    fontSize: 15,
    marginBottom: 12,
  },
  startButton: {
    backgroundColor: "#ef4444",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  startButtonText: { color: "#ffffff", fontSize: 15, fontWeight: "700" },
  historyCard: {
    marginHorizontal: 12,
    marginVertical: 5,
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    padding: 12,
  },
  historyTitle: { fontSize: 14, fontWeight: "600", color: "#d1d5db", marginBottom: 4 },
  historyMeta: { fontSize: 12, color: "#6b7280" },
});
