import { createThemeStyles } from "./createThemeStyles";

export const profileStyles = createThemeStyles({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#fff",
  },
  profileHeader: {
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  displayName: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
  },
  info: {
    fontSize: 16,
    marginBottom: 5,
    color: "#666",
  },
  editContainer: {
    marginBottom: 20,
    gap: 12,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: "#fff",
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  secondaryButton: {
    backgroundColor: "#3a3a3a",
    flex: 1,
  },
  button: {
    backgroundColor: "#e74c3c",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  logoutButton: {
    backgroundColor: "#999",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  footprintToggleButton: {
    marginTop: 20,
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#e74c3c",
  },
  footprintToggleText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
  },
  footprintContainer: {
    marginBottom: 20,
    backgroundColor: "#fafafa",
    borderRadius: 8,
    paddingVertical: 8,
  },
  footprintLockedContainer: {
    marginBottom: 20,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  footprintLockedText: {
    textAlign: "center",
    color: "#374151",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 4,
  },
  footprintLockedSubText: {
    textAlign: "center",
    color: "#6b7280",
    fontSize: 12,
  },
  footprintItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footprintName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    flex: 1,
  },
  footprintDate: {
    fontSize: 12,
    color: "#999",
  },
  noFootprintText: {
    textAlign: "center",
    paddingVertical: 20,
    color: "#999",
    fontSize: 13,
  },
  receiveFilterContainer: {
    marginTop: 20,
    marginBottom: 12,
    backgroundColor: "#f9fafb",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  rankGuideContainer: {
    marginTop: 4,
    marginBottom: 12,
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  rankGuideTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  rankGuideSubtitle: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 10,
  },
  rankGuideRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#edf2f7",
  },
  rankGuideLabel: {
    flex: 1,
    fontSize: 13,
    color: "#374151",
    fontWeight: "600",
    marginRight: 8,
  },
  rankGuideDone: {
    fontSize: 12,
    color: "#059669",
    fontWeight: "700",
  },
  rankGuideTodo: {
    fontSize: 12,
    color: "#dc2626",
    fontWeight: "700",
  },
  receiveFilterTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  receiveFilterDescription: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 12,
  },
  receiveFilterToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
  },
  receiveFilterLabel: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "500",
  },
  receiveFilterValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#e74c3c",
  },
  membershipContainer: {
    marginTop: 8,
    marginBottom: 12,
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 10,
  },
  membershipTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
  },
  membershipCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  membershipLabel: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: "600",
    marginBottom: 4,
  },
  membershipHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  membershipCancelButton: {
    backgroundColor: "#fee2e2",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  membershipCancelButtonText: {
    color: "#b91c1c",
    fontSize: 12,
    fontWeight: "700",
  },
  membershipValue: {
    fontSize: 18,
    color: "#111827",
    fontWeight: "800",
    marginBottom: 4,
  },
  membershipMeta: {
    fontSize: 12,
    color: "#4b5563",
    lineHeight: 18,
  },
});
