import { createThemeStyles } from "./createThemeStyles";

export const qrStyles = createThemeStyles({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
  description: {
    fontSize: 13,
    color: "#555",
    marginBottom: 10,
    textAlign: "center",
  },
  expireText: {
    fontSize: 13,
    color: "#15803d",
    marginBottom: 10,
    fontWeight: "600",
  },
  completedBox: {
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 12,
  },
  completedText: {
    color: "#2e7d32",
    fontWeight: "600",
  },
  cancelledBox: {
    width: "100%",
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 12,
  },
  cancelledText: {
    color: "#374151",
    fontWeight: "600",
    textAlign: "center",
  },
  reportedBox: {
    width: "100%",
    backgroundColor: "#fef2f2",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  reportedText: {
    color: "#b91c1c",
    fontWeight: "600",
    textAlign: "center",
  },
  unavailableBox: {
    width: "100%",
    backgroundColor: "#eff6ff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  unavailableText: {
    textAlign: "center",
    color: "#1d4ed8",
    fontSize: 13,
    fontWeight: "600",
  },
  distanceBox: {
    width: "100%",
    backgroundColor: "#f0fdf4",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  distanceText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#14532d",
    textAlign: "center",
  },
  distanceStatus: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  distanceStatusIn: {
    color: "#15803d",
  },
  distanceStatusOut: {
    color: "#b45309",
  },
  distanceMeta: {
    marginTop: 4,
    fontSize: 11,
    color: "#374151",
    textAlign: "center",
  },
  qrContainer: {
    width: "100%",
    padding: 20,
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    marginBottom: 20,
    alignItems: "center",
  },
  qrCode: {
    fontSize: 16,
    fontWeight: "bold",
  },
  qrImage: {
    width: 240,
    height: 240,
    marginBottom: 10,
  },
  qrTokenText: {
    fontSize: 12,
    color: "#374151",
    textAlign: "center",
    fontWeight: "600",
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  button: {
    backgroundColor: "#e74c3c",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
    width: "100%",
  },
  verifyButton: {
    backgroundColor: "#16a34a",
  },
  scanButton: {
    backgroundColor: "#2563eb",
  },
  troubleContainer: {
    width: "100%",
    marginTop: 6,
  },
  cancelButton: {
    backgroundColor: "#6b7280",
  },
  reportButton: {
    backgroundColor: "#dc2626",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  scannerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 16,
  },
  scannerCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 14,
  },
  scannerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    textAlign: "center",
  },
  scannerDescription: {
    marginTop: 6,
    marginBottom: 12,
    color: "#4b5563",
    fontSize: 12,
    textAlign: "center",
  },
  cameraView: {
    width: "100%",
    height: 320,
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 10,
  },
  scannerCloseButton: {
    backgroundColor: "#6b7280",
    marginBottom: 0,
  },
});
