import { createThemeStyles } from "./createThemeStyles";

export const searchStyles = createThemeStyles({
  container: {
    flex: 1,
    padding: 14,
    backgroundColor: "#fff",
  },
  filterContainer: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
  },
  filterHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  capabilityText: {
    fontSize: 12,
    color: "#374151",
    fontWeight: "600",
    flex: 1,
  },
  filterToggleButton: {
    backgroundColor: "#e5e7eb",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  filterToggleButtonText: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "700",
  },
  lockGuideCard: {
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  lockGuideTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  lockGuideText: {
    fontSize: 12,
    color: "#4b5563",
    marginBottom: 6,
  },
  lockGuideProgressText: {
    fontSize: 12,
    color: "#374151",
    fontWeight: "700",
    marginBottom: 8,
  },
  lockGuideButton: {
    alignSelf: "flex-start",
    borderRadius: 8,
    backgroundColor: "#374151",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  lockGuideButtonText: {
    fontSize: 12,
    color: "#f9fafb",
    fontWeight: "700",
  },
  filterSummaryText: {
    fontSize: 12,
    color: "#4b5563",
    fontWeight: "600",
    marginBottom: 2,
  },
  validationMessage: {
    fontSize: 12,
    color: "#dc2626",
    fontWeight: "700",
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 9,
    marginBottom: 10,
    borderRadius: 6,
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  chip: {
    backgroundColor: "#e0e7ff",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#c7d2fe",
  },
  chipActive: {
    backgroundColor: "#4f46e5",
    borderColor: "#4338ca",
  },
  chipText: {
    fontSize: 12,
    color: "#4f46e5",
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#ffffff",
  },
  inputDisabled: {
    backgroundColor: "#e5e7eb",
    color: "#6b7280",
  },
  button: {
    backgroundColor: "#e74c3c",
    padding: 10,
    borderRadius: 6,
    alignItems: "center",
    flex: 1,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 8,
  },
  buttonRowCompact: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  clearButton: {
    backgroundColor: "#6b7280",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  userItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    backgroundColor: "#fff",
    borderRadius: 8,
    marginBottom: 6,
  },
  userName: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  userFactRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 6,
  },
  userFactChip: {
    backgroundColor: "#f3f4f6",
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    maxWidth: "100%",
  },
  userFactText: {
    fontSize: 11,
    color: "#374151",
    fontWeight: "600",
  },
  requestStatusBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 6,
  },
  requestStatusPending: {
    backgroundColor: "#dbeafe",
  },
  requestStatusMatched: {
    backgroundColor: "#dcfce7",
  },
  requestStatusExpired: {
    backgroundColor: "#fee2e2",
  },
  requestStatusPassed: {
    backgroundColor: "#e5e7eb",
  },
  requestStatusText: {
    fontSize: 11,
    color: "#1f2937",
    fontWeight: "700",
  },
  requestDeadlineText: {
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  requestDeadlineNormal: {
    color: "#2563eb",
  },
  requestDeadlineSoon: {
    color: "#dc2626",
  },
  requestDeadlineExpired: {
    color: "#7c2d12",
  },
  userBio: {
    fontSize: 14,
    color: "#666",
  },
  userBioEmpty: {
    color: "#9ca3af",
  },
  cardActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  profileButton: {
    backgroundColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 40,
    justifyContent: "center",
  },
  profileButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  chatButton: {
    backgroundColor: "#e74c3c",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 40,
    justifyContent: "center",
  },
  chatButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  pendingButton: {
    backgroundColor: "#9ca3af",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 40,
    justifyContent: "center",
    opacity: 0.9,
  },
  pendingButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  relikeButton: {
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 40,
    justifyContent: "center",
  },
  relikeButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  passButton: {
    backgroundColor: "#6b7280",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 40,
    justifyContent: "center",
  },
  passButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  userMeta: {
    fontSize: 12,
    color: "#374151",
    marginBottom: 4,
    fontWeight: "600",
  },
  emptyText: {
    textAlign: "center",
    marginTop: 20,
    fontSize: 16,
    color: "#999",
  },
  resultCountText: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "700",
  },
  resultHeaderRow: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  sortToggleRow: {
    flexDirection: "row",
    gap: 6,
  },
  sortToggleButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#f9fafb",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  sortToggleButtonActive: {
    borderColor: "#2563eb",
    backgroundColor: "#dbeafe",
  },
  sortToggleButtonText: {
    fontSize: 11,
    color: "#4b5563",
    fontWeight: "700",
  },
  sortToggleButtonTextActive: {
    color: "#1d4ed8",
  },
  activeFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  activeFilterHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  activeFilterHeaderText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#374151",
  },
  activeFilterClearAllButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#c7d2fe",
  },
  activeFilterClearAllText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#4338ca",
  },
  activeFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activeFilterChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#374151",
  },
  activeFilterChipRemove: {
    fontSize: 12,
    lineHeight: 12,
    color: "#6b7280",
    fontWeight: "700",
  },
});
